directory:
  - deploy/
skip-check:
  - CKV_AZURE_1
quiet: true
soft-fail: true
output-format: junitxml
framework: bicep
log-level: WARNING
external-checks-git: https://github.com/SebastianGredal/shared-checkov-policies.git//checks/bicep