directory:
  - deploy/
skip_check:
  - CKV_AZURE_1
quiet: true
soft_fail: true
output_format: junitxml
framework: bicep
log_level: WARNING
external-checks-git: https://github.com/SebastianGredal/shared-checkov-policies.git//checks/bicep