name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:      
  dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: SebastianGredal/demo-project/.github/workflows/deployment.yml@main
        with:
          environment: dev
  prod:
    needs: [dev]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: SebastianGredal/demo-project/.github/workflows/deployment.yml@main
        with:
          environment: prod
