name: Deployment

on: [workflow_dispatch]

env:
  location: westeurope

jobs:
  Deployment:
    name: Deployment of Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}
      - name: Bicep IaC - validation
        uses: azure/arm-deploy@v1
        with:
          deploymentName: Validation-${{ github.run_number }}
          deploymentMode: Validate
          scope: subscription
          region: ${{ env.location }}
          template: deploy/resourceGroup.bicep
      - name: Bicep IaC - what if
        uses: azure/arm-deploy@v1
        with:
          deploymentName: what-if-${{ github.run_number }}
          deploymentMode: Incremental
          scope: subscription
          region: ${{ env.location }}
          template: deploy/resourceGroup.bicep
          additionalArguments: "--what-if"
      - name: Bicep IaC - Deployment
        uses: azure/arm-deploy@v1
        with:
          deploymentName: deployment-${{ github.run_number }}
          deploymentMode: Incremental
          scope: subscription
          region: ${{ env.location }}
          template: deploy/resourceGroup.bicep
          additionalArguments: "--rollback-on-error"
