name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  location: westeurope

jobs:      
  deploy:
    name: Deployment to ${{ inputs.environment }} Environment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}
      - name: Bicep IaC - validation
        uses: azure/arm-deploy@v1
        with:
          deploymentName: Validation-${{ github.run_number }}
          deploymentMode: Validate
          scope: subscription
          region: ${{ env.location }}
          template: deploy/resourceGroup.bicep
          parameters: environment="${{ inputs.environment }}" environmentVersion="${{ github.run_number }}"
      - name: Bicep IaC - what if
        uses: azure/arm-deploy@v1
        with:
          deploymentName: what-if-${{ github.run_number }}
          scope: subscription
          region: ${{ env.location }}
          template: deploy/resourceGroup.bicep
          parameters: environment="${{ inputs.environment }}" environmentVersion="${{ github.run_number }}"
          additionalArguments: "--what-if"
      - name: Bicep IaC - Deployment
        uses: azure/arm-deploy@v1
        with:
          deploymentName: deployment-${{ github.run_number }}
          scope: subscription
          region: ${{ env.location }}
          parameters: environment="${{ inputs.environment }}" environmentVersion="${{ github.run_number }}"
          template: deploy/resourceGroup.bicep
